project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
  
website:
  title: "Morgan Ryan"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - Maps.qmd
      - Data-Acquisition.qmd 
      - Text-Analysis.qmd
format:
  html:
    theme: cosmo
    toc: true
  

editor: visual

